### ISSUE TITLE
Decrease Docker image size

### ISSUE THREAD

**Issue by ryansurf** [ryansurf/cli-surf#113]
Currently we are using the stock Python image in our [Dockerfile](https://github.com/ryansurf/cli-surf/blob/main/Dockerfile).

We can make this smaller, perhaps by using the python-slim image.

**Comment by hotpocket** [comment]
making smaller images is a laudable goal, I'll take this.  probably not the proper place to comment but there are more words on this in [the closed PR](https://github.com/ryansurf/cli-surf/pull/107#issuecomment-2284830127)

**Comment by hotpocket** [comment]
it may be a week before I can get to this 1.  If someone else wants it in the interim that's fine. otherwise i'll have time to dig into this early next week.

**Comment by ryansurf** [comment]
@hotpocket no worries, Docker works now so its not urgent. Let me know if anything changes 👍
