### ISSUE TITLE
Create Docs

### ISSUE THREAD

**Issue by ryansurf** [ryansurf/cli-surf#12]
Perhaps should create a wiki/docs for the project

**Comment by K-dash** [comment]
If you're planning to write documentation, my recommendation is to use `MKdocs` and publish it on GitHub Pages! 
I'm here to help you out 🥳

https://squidfunk.github.io/mkdocs-material/publishing-your-site/

**Comment by ryansurf** [comment]
Nice! Debating how I want to set this up, I have something runnign on GH pages already... unless I can run a page per repo?

**Comment by ryansurf** [comment]
@K-dash [deployed!](https://ryansurf.github.io/cli-surf/)

**Comment by K-dash** [comment]
@ryansurf 
Nice! You work fast hehe
