### ISSUE TITLE
Cancel button does nothing in frontend

### ISSUE THREAD

**Issue by ryansurf** [ryansurf/cli-surf#13]
In the frontend, the "cancel" button does nothing. It should clear whatever text is in the text field("pipeline" in the video).
[video.webm](https://github.com/ryansurf/cli-surf/assets/94500732/3de1ed68-dd60-4365-9580-73902fdc5445)

**Comment by rabelmervin** [comment]
Hi sir, I can solve this issue, Could you please tell me the location of this issue's code in the repository ????

**Comment by ryansurf** [comment]
Hi @rabelmervin, welcome. Yes, go for it! The frontend is in src/frontend. 

Check the readme for instructions on how to get it running, let me know if you have any issues

**Comment by ryansurf** [comment]
@rabelmervin were you able to get the frontend up?

**Comment by rabelmervin** [comment]
@ryansurf yes sir, Frontend is running well.

**Comment by rabelmervin** [comment]
@ryansurf Sir I solved the issue using <script> tag inside the html file but, if i use the same code is inside the script.js file its not working. Is it ok to implement the code inside the html itself or you wanna change it sir ????

**Comment by ryansurf** [comment]
@rabelmervin thats ok! Go ahead and submit a pull request, I'll see if I can get it working inside script.js😁

**Comment by rabelmervin** [comment]
@ryansurf Sir I submitted the pull request did you got the request ????

**Comment by ryansurf** [comment]
@rabelmervin yeah, looks great! I'll approve it when I get home later today, good work
