### ISSUE TITLE
Streamlit is broken!

### ISSUE THREAD

**Issue by ryansurf** [ryansurf/cli-surf#135]
When querying a surf report on streamlit, we get the following error:

```
KeyError: 'height'
Traceback:
File "/home/ryan/.cache/pypoetry/virtualenvs/cli-surf-WsVlPvL3-py3.11/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 75, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "/home/ryan/.cache/pypoetry/virtualenvs/cli-surf-WsVlPvL3-py3.11/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 574, in code_to_exec
    exec(code, module.__dict__)
File "/home/ryan/ryan/code/cli-surf/src/dev_streamlit.py", line 85, in <module>
    df = sl_help.graph_data(report_dict, graph_type)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ryan/ryan/code/cli-surf/src/streamlit_helper.py", line 68, in graph_data
    forecasted_heights = [
                         ^
File "/home/ryan/ryan/code/cli-surf/src/streamlit_helper.py", line 69, in <listcomp>
    forecast["height"] for forecast in report_dict["Forecast"]
    ~~~~~~~~^^^^^^^^^^
```

Apparently there's a key error. Recently, the names of the forecast keys have been changed. Look at the `graph_data()` function in `streamlit_helper.py` and the `forecast_to_json` function in `helper.py` to get an idea of the updated key names!

Note: This is meant to be a beginner-friendly issue. I've solved this myself, if you need help please ping me! To run streamlit, please refer to the README

**Comment by balugans** [comment]
Hi 

I would like to help.

**Comment by balugans** [comment]
I tried running streamlit run src/dev_dreamlit.py and i get following error: ModuleNotFoundError: No module named 'streamlit_folium'

**Comment by balugans** [comment]
> I tried running streamlit run src/dev_dreamlit.py and i get following error: ModuleNotFoundError: No module named 'streamlit_folium'. How do i resolve the error?

I did pip install streamlit-folium. The best way would be to add streamlit-folium to pyproject.toml

**Comment by ryansurf** [comment]
> > I tried running streamlit run src/dev_dreamlit.py and i get following error: ModuleNotFoundError: No module named 'streamlit_folium'. How do i resolve the error?
> 
> I did pip install streamlit-folium. The best way would be to add streamlit-folium to pyproject.toml

Did you run `make install`?

**Comment by balugans** [comment]
> > > I tried running streamlit run src/dev_dreamlit.py and i get following error: ModuleNotFoundError: No module named 'streamlit_folium'. How do i resolve the error?
> > 
> > 
> > I did pip install streamlit-folium. The best way would be to add streamlit-folium to pyproject.toml
> 
> Did you run `make install`?

yes  and i think streamlit-folium is not present in the toml file

**Comment by balugans** [comment]
i just did a PR after the fix . please review the changes

**Comment by ryansurf** [comment]
#136
