### ISSUE TITLE
Streamlit fails because of missing module.

### ISSUE THREAD

**Issue by balugans** [ryansurf/cli-surf#139]
Running streamlit run src/dev_dreamlit.py and i get following error: ModuleNotFoundError: No module named 'streamlit-folium'.

Solution will be add the package streamlit-folium' to pyproject.toml

**Comment by balugans** [comment]
I have the fix here [PR#140](https://github.com/ryansurf/cli-surf/pull/140)

**Comment by ryansurf** [comment]
@balugans 

Looks great! The version is the latest, so it should be a-ok. Thanks 😄

**Comment by balugans** [comment]
Thanks for allowing me to contribute!
