### ISSUE TITLE
Pytest GPT error

### ISSUE THREAD

**Issue by ryansurf** [ryansurf/cli-surf#146]
Pytest is [failing](https://github.com/ryansurf/cli-surf/actions/runs/11128485904/job/30923319691) due to the `test_print_gpt()` function in `tests/test_helper.py`.

The reason for this is we are giving the input: `"Please output 'gpt works'"` to the GPT and checking if "gpt_works" is in the response for the test. However, now the gpt responds with: `'I\'m sorry, but I cannot directly display text within a specific format or based on real-time information. However, I...\n\nPlease replace \'test test\', \'test degrees\', and \'test seconds\' with the actual values for a specific output.'`.

We may have to come up with a more clever prompt!

**Comment by macnult** [comment]
Submitted a PR with confidence about this but it appears to be passing/failing without consistency, especially with the last commit.
