### ISSUE TITLE
GPT argument 

### ISSUE THREAD

**Issue by ryansurf** [ryansurf/cli-surf#27]
Would be cool to pass an arg like `gpt` to use a service like [this](https://github.com/xtekky/gpt4free?tab=readme-ov-file#text-generation) to generate a surf report based on the current data

**Comment by ryansurf** [comment]
Can also have a .env var to set data like: skill level, board size, etc that is passed as an arg to the gpt

**Comment by K-dash** [comment]
Hey, that's a pretty cool idea!  With GPT, the possibilities are endless.🤯
Of course, we'll need to put our heads together and figure out the best ways to harness its power.

**Comment by ryansurf** [comment]
@K-dash I'm thinking of using the [repo](https://github.com/xtekky/gpt4free?tab=readme-ov-file#text-generation) linked above, really easy to set up. 

The problem is, the model it uses is a bit... stupid. I think we can have two options, use the default model as the one above, or, if the user has an API key for some other model(OpenAI or similar), they can use that insead.

**Comment by ryansurf** [comment]
So I've implemented this commit b19db65 which adds the basic functionality.  It is failing the tests with a `ModuleNotFoundError`, going to debug that one later :sweat_smile:

The helper.py code is getting messy, I need to dedicate some time to clean it up lol

**Comment by K-dash** [comment]
@ryansurf 
> Weird thing happened though, I used pipreqs to remake the requirements.txt file and it didn't add the email_validator module, so testing failed (only in GH Actions, not my local setup). I had to manually add this module to the requirements,


Hmm, that's odd. [This PR](https://github.com/ryansurf/cli-surf/pull/28/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552) , it clearly shows that you added `email_validator` to the `requirements.txt` file.

It's possible that something might have accidentally caused a regression. 🤔

**Comment by ryansurf** [comment]
openai gpt added! 0b0dfb32c94d787e8ff87f06bd806e998bc7e415
