### ISSUE TITLE
Introducing pre-commit hooks

### ISSUE THREAD

**Issue by K-dash** [ryansurf/cli-surf#29]
@ryansurf 
I've been noticing that our CI keeps failing whenever we forget to run the Linter/Formatter before committing our code.

https://github.com/ryansurf/cli-surf/pull/28/commits/85582c8a3eabcc9653380fe60461ff3e5d32b445

So, I was thinking, why don't we introduce `pre-commit` hooks to our workflow?
That way, the Linter/Formatter will run automatically every time we commit, ensuring that our code is always in tip-top shape!

f you're on board with this idea, just give me a shout, and I'll be more than happy to set it up 🙌

**Comment by ryansurf** [comment]
I actually had this set up for the black formatter but forgot to commit the code, deleted the repo and now i dont have it :expressionless:

Im on board, lets do it!

**Comment by K-dash** [comment]
Happy to help! I'll get right on it 👍
