### ISSUE TITLE
Frontend output in a form/textbox

### ISSUE THREAD

**Issue by ryansurf** [ryansurf/cli-surf#39]
When getting a surf report in the frontend, the output look like this:

![image](https://github.com/ryansurf/cli-surf/assets/94500732/742c7b13-a8ef-4326-892a-704023a86de1)

(Output starts with `Location: Steamer Lane...`). This would look much better if it were in some kind of form/textbox (maybe white? whatever you think looks best is fine). 

For reference, I'm thinking the output would look good if it were in something like:
![image](https://github.com/ryansurf/cli-surf/assets/94500732/728cb68b-43cd-474d-859d-c2a4b9c64e1a)

**Comment by death12239** [comment]
Good day, I would love to be assigned this request. Thank you
