### ISSUE TITLE
More data

### ISSUE THREAD

**Issue by ryansurf** [ryansurf/cli-surf#4]
At the moment, there is not that much data(only wave height, direction, period)

We can use more weather-related data. The weather data API documentation is [here](https://open-meteo.com/en/docs). 

Some ideas: rain, temperature, windspeed, etc.

**Comment by MylesPerHour201** [comment]
Hi, @ryansurf,  I'd like to work on this issue if available.

**Comment by MylesPerHour201** [comment]
Thank you @ryansurf if there are not parameters to exclude between daily/hourly/current weather variables, I wanted to at least at visibility, cloud cover total and  UV Index, with potential to add more if I find relevancy.
