### ISSUE TITLE
Replace Docker base image to reduce # of open-source vulnerabilities

### ISSUE THREAD

**Issue by Hummus-Ful** [ryansurf/cli-surf#52]
I suggest to replace the Docker base image currently being used by python:alpine one in order to:
1. Reduce the number of open-source vulnerabilities exists in [python:3.12.3-slim](https://hub.docker.com/layers/library/python/3.12.3-slim/images/sha256-fd3817f3a855f6c2ada16ac9468e5ee93e361005bd226fd5a5ee1a504e038c84?context=explore) base image by using [python:alpine3.20](https://hub.docker.com/layers/library/python/alpine3.20/images/sha256-ebe4166fcf7fd212975cb932440ba69cfd6c27fdb9ab2253f965a1d2d7f1c476?context=explore) instead.
2. Reduce the final Docker image size from 549MB to 486MB
![slim_vs_alpine](https://github.com/user-attachments/assets/2e074dad-4dfd-456d-ba25-0cafd63fc325)

**Comment by ryansurf** [comment]
Hey @Hummus-Ful, welcome! I think that's a solid idea, have you tested to make sure that all dependencies still work with alpine?

If so, let's go for it

**Comment by Hummus-Ful** [comment]
Hey @ryansurf,
Yes, I've tested the API manually and ran both `make test` and `make test_docker` and all 9 tests passed successfully.

**Comment by ryansurf** [comment]
@Hummus-Ful awesome, did you want to submit a PR for this? I can do it too, up to you

**Comment by Hummus-Ful** [comment]
PR created: #53
