### ISSUE TITLE
Introduction of AI-Driven Code Review Tools

### ISSUE THREAD

**Issue by K-dash** [ryansurf/cli-surf#59]
@ryansurf 
I have a suggestion. 
There are several tools that allow AI to conduct code reviews when sending pull requests, so why not try introducing one? The following blog introduces some of these tools:

https://www.morningdough.com/ai-tools/best-ai-code-analyzers/

Some notable examples include Codacy, CodeClimate, and Sourcery. If you're introducing these to an OSS public repository, you can use them completely free of charge.
I think any of these tools would be fine, but I'm personally interested in Sourcery or Codacy!

**Comment by ryansurf** [comment]
This would be awesome. I read the article & checked out your suggestions, Sourcery and CodeClimate caught my attention.

Lets implement one of these. I'll be on vacation until Sunday, but if you'd want to get started on it, go for it! We can also collaborate and take some more time decide on a platform when I'm back.

I'm excited to get this going, haha

**Comment by K-dash** [comment]
Thank you for accepting the suggestion!
Since we are in agreement, shall we try using Sourcery:)

To start using Sourcery, it seems that the repository owner needs to link Sourcery with the repository.
Could you please handle the integration from the following link?

https://sourcery.ai/

**Comment by ryansurf** [comment]
@K-dash I linked Sourcery with the repo, I think it should be working now! I suppose we'll find out on the next PR, haha

**Comment by K-dash** [comment]
@ryansurf 
Nice! Sourcery is doing a great job🥳 Thanks!
