### ISSUE TITLE
make cli args prettier

### ISSUE THREAD

**Issue by ryansurf** [ryansurf/cli-surf#7]
At the moment, we use the app with something like: `curl localhost:8000?args=fc=3,hdate,loc=trestles`

The `args=` seems unnecessary. Look into how can can get ride of this, so we can have something like:

`curl localhost:8000?fc=3,hdate,loc=trestles` instead. Should work in `server.py` and maybe `main.py`

**Comment by K-dash** [comment]
@ryansurf 

Hello!
This is an interesting project you have here!
I discovered this repository through the `help wanted` tag.

Regarding this issue, if it's just a matter of removing the `args=` prefix to make it unnecessary, it seems like a straightforward fix. Would it be okay if I took care of it?

**Comment by ryansurf** [comment]
Hey @K-dash, welcome and thank you! Yes, that would be awesome. However, I was messing around with it for a few minutes and it may not be that simple - maybe I'm wrong.

I think you would mostly be working in either `main.py`, `server.py`. Let me know if you have any issues!

Were you able to get the app up and running? I'm working on cleaning up code and making the readme more simple but its a work in progress

**Comment by K-dash** [comment]
Thank you very much!
The readme is clear and easy to follow, and I was able to start the app without any issues by following the steps outlined.
I will submit a pull request, so please keep an eye out for it :)
