### ISSUE TITLE
Automate Contributors Section in `README.md`

### ISSUE THREAD

**Issue by K-dash** [ryansurf/cli-surf#83]
@ryansurf 
There's an open-source tool available to automate the [Contributors section](https://github.com/ryansurf/cli-surf?tab=readme-ov-file#-contributors) in our `README.md`.

The tool is called All Contributors.
https://allcontributors.org/

I highly recommend implementing this tool as it will significantly streamline the process of updating and maintaining our list of contributors!😊
(I intended to implement this myself, but I couldn't proceed because the repository owner needs to install the All Contributors bot😭)

**Comment by ryansurf** [comment]
Nice! I agree, that looks like a better option. I'll work on it today 😸

**Comment by ryansurf** [comment]
Greeting @K-dash, 

The bot is now installed! Do you still want to work on the implementation? If not, I can

One think i'd like to do with the bot is automate the adding of contributors to the table - it seems like the default is to use the `@all-contributors add <user>` command. It [seems](https://allcontributors.org/docs/en/cli/overview) like we'd be able to do this, but I haven't started incase you wanna take a shot at it. Let me know!

**Comment by K-dash** [comment]
@ryansurf 
Thank you for the implementation! I'll go ahead and try calling the bot in some past PRs😊

**Comment by K-dash** [comment]
Hi @ryansurf 

![image](https://github.com/user-attachments/assets/b2a2d45f-931d-49c9-8035-6c3108aa3322)

By calling the bot in [this PR](https://github.com/ryansurf/cli-surf/pull/89), Ryan has been added!
Probably, if we call the bot in past PRs where the all-contributors definition doesn't exist in the `README.md` yet, it might not work properly. 　↓

https://github.com/ryansurf/cli-surf/pull/14#issuecomment-2273886878

**Comment by ryansurf** [comment]
@K-dash 

Ah, that makes sense. I was going to add all the past contributors. I suppose I'll call the bot and add everyone on this PR

**Comment by ryansurf** [comment]
@all-contributors please add @rabelmervin for code

**Comment by ryansurf** [comment]
@all-contributors please add @death12239 for code

**Comment by ryansurf** [comment]
@all-contributors please add @shaifulazh for code

**Comment by ryansurf** [comment]
@all-contributors please add @Hummus-Ful for infra. please add @vaibhav-2703 for code.

**Comment by ryansurf** [comment]
@all-contributors please add @vaibhav-2703 for code

**Comment by ryansurf** [comment]
@all-contributors please add @Rajiv-Rago for code

**Comment by ryansurf** [comment]
@all-contributors please add @Ulises-Sanch3z for code

**Comment by ryansurf** [comment]
@all-contributors please add @avkoll for code

**Comment by ryansurf** [comment]
@all-contributors please add @mrmcgrain for code

**Comment by ryansurf** [comment]
@all-contributors please add @vaibhav-2703 for code

**Comment by ryansurf** [comment]
@all-contributors please add @K-dash for tests, ideas, questions

**Comment by ryansurf** [comment]
@all-contributors please add @ryansurf for tests, ideas, questions

**Comment by ryansurf** [comment]
https://github.com/all-contributors please add @K-dash  for tests, ideas, questions

**Comment by ryansurf** [comment]
@all-contributors please add @K-dash for tests, ideas, questions

**Comment by ryansurf** [comment]
@all-contributors please add @rabelmervin for code

**Comment by ryansurf** [comment]
@all-contributors please add @rabelmervin for code

**Comment by ryansurf** [comment]
@all-contributors please add @vaibhav-2703 for code

**Comment by ryansurf** [comment]
@all-contributors please add @NandaniThakur for code
